# Set the variables as Bitbucket env vars
# Go to the repo settings > Pipelines > Deployments > Variables

image: instrumentisto/rsync-ssh

definitions:
  caches:
    composer-tmp: /tmp/cache
  steps:
    - step: &build-frontend
        name: Build frontend files
        image: node:10
        caches:
          - node
        script:
          - npm install # Use install instead of ci for better cache
          - npm run build
        artifacts:
          - assets/dist/**
    - step: &build-php
        name: Build PHP files
        image: composer:2
        caches:
          - composer-tmp
        script:
          - composer install
          - composer run-script lint
          - composer update --no-dev --optimize-autoloader
        artifacts:
          - vendor/**

pipelines:
  branches:
    master:
      - step: *build-frontend
      - step: *build-php
      - step:
          name: Deploy to production
          deployment: production # This selects the production variables
          script:
            - rsync -azh --stats -e "ssh -p $PORT" --exclude-from '.rsyncignore' . $DESTINATION
    staging:
      - step: *build-frontend
      - step: *build-php
      - step:
          name: Deploy to staging
          deployment: staging # This selects the staging variables
          script:
            - rsync -azh --stats -e "ssh -p $PORT" --exclude-from '.rsyncignore' . $DESTINATION
