name: Build and deploy

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Build frontend
        run: |
          npm ci
          npm run lint
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: assets/dist/

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action/7.4/install@master
        with:
          args: install
      - name: Build backend
        run: |
          composer run-script lint
          composer update --no-dev --optimize-autoloader
      - uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor/

  deploy:
    needs: [build-frontend, build-backend]
    if: github.ref == 'refs/heads/master' # Runs on master only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: assets/dist/
      - uses: actions/download-artifact@v2
        with:
          name: vendor
          path: vendor/
      - name: Deploy to production
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          flags: -azh --stats
          options: --exclude-from .rsyncignore
          # ssh_options: -p ${{ secrets.PORT }}
          src: '.'
          dest: ${{ secrets.DESTINATION }}
